### ISSUE TITLE
Todo List

### ISSUE THREAD

**Issue by kreimben** [kreimben/ZeroTwo_bot#6]
For zerotwo 4.0, I have to implement below.

- [x] Implement responsive website.
- [x] Connect gRPC server and frontend service.
- [x] Basic control of music bot.
